language: android
jdk: oraclejdk8
sudo: false
dist: precise
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25
     #sys-img-armeabi-v7a-android-22 #emulator
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-21
    - extra
before_script:
        - chmod +x gradlew      #Grand permissions
        - android list targets
        - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
        - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

script:
   - ./gradlew build connectedCheck


before_install:
   - chmod +x gradlew